apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: voting-app-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  iops: "100"
  throughput: "125"
  encrypted: "true"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
